"""
================================================================================
Example: Binary Saturation Classifier for Land Parcels
================================================================================
This script provides a REFERENCE IMPLEMENTATION of the TensorFlow/Keras binary
classifier used in Stage 6 (Availability Filtering) to determine whether a
commercially zoned parcel is "saturated" (fully built out) or "unsaturated"
(has remaining development potential).

PURPOSE:
    This is an EXAMPLE, not a turnkey solution. The specific feature set,
    model architecture, and hyperparameters should be adapted to your own
    study area and data. The architecture shown here achieved ~70% balanced
    accuracy in the GTHA case study.

HOW TO USE:
    1. Prepare a labelled dataset of parcels (see "Data Requirements" below)
    2. Adapt the FEATURE_COLUMNS list to match your available features
    3. Run this script to train and evaluate the classifier
    4. Apply the trained model to label all remaining parcels

DATA REQUIREMENTS:
    A CSV file with one row per parcel, containing:
      - A binary label column: 0 = Saturated, 1 = Unsaturated
      - Feature columns (examples listed below — adapt to your data)

    The training labels should be generated by visual inspection of
    high-resolution satellite imagery, cross-referenced with building
    footprint data and spatio-temporal records of existing structures.
    A balanced sample (roughly equal 0s and 1s) is recommended.

DISCLOSURE:
    Code cleaned and reorganised with the assistance of Claude AI (Anthropic).
================================================================================
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.utils import class_weight
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, BatchNormalization, Dropout
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping

# ==============================================================================
# USER CONFIGURATION — Adapt these to your data
# ==============================================================================

# Path to the labelled parcel dataset (CSV)
INPUT_PATH = "path/to/your/labelled_parcels.csv"     # <-- REPLACE WITH YOUR PATH

# Name of the binary label column (0 = Saturated, 1 = Unsaturated)
LABEL_COLUMN = "Label"

# Feature columns used for classification.
# These should capture the PHYSICAL state of the parcel and its surroundings
# to predict whether the parcel has remaining development capacity.
#
# The features below are representative of what was used in the GTHA case
# study. Replace or extend this list based on your available data.
FEATURE_COLUMNS = [
    # -- Parcel geometry --
    "Parcel_Area",          # Parcel area (m²)
    "P_Perim",              # Parcel perimeter (m)
    "CH_Area",              # Convex hull area (m²)
    "CNV",                  # Convexity index (area / convex hull area)
    "FR",                   # Fractality index
    "REC",                  # Rectangularity index
    "PP_CI",                # Polsby-Popper compactness index

    # -- Environmental / contextual (1km buffer) --
    "ANSI_A_1km",           # Area of natural significance within 1km (m²)
    "WATB_A_1km",           # Waterbody area within 1km (m²)
    "WETL_A_1km",           # Wetland area within 1km (m²)
    "FLX_A_1km",            # Flex/open space area within 1km (m²)
    "BF_A_1km",             # Total building footprint area within 1km (m²)

    # -- Land use composition (1km buffer) --
    "IND_A_1km",            # Industrial area within 1km (m²)
    "OFC_A_1km",            # Office area within 1km (m²)
    "RTL_A_1km",            # Retail area within 1km (m²)
    "ResAll_C_1km",         # Residential building count within 1km

    # -- Infrastructure (1km buffer) --
    "HWY_L_1km",            # Highway length within 1km (m)
    "MJLC_RDS_L_1km",      # Major road length within 1km (m)
    "TRAN_RTS_L_1km",       # Transit route length within 1km (m)
    "TRAN_STP_C_1km",       # Transit stop count within 1km

    # -- Micro-environment (100m buffer) --
    "BUID_A_100m",          # Building footprint area within 100m (m²)
    "FLX_RBA_100m",         # Flex/open space ratio within 100m
    "IND_RBA_100m",         # Industrial ratio within 100m
    "OFC_RBA_100m",         # Office ratio within 100m
    "RTL_RBA_100m",         # Retail ratio within 100m
    "ResAll_C_100m",        # Residential building count within 100m
    "MJLC_RDS_L_100m",     # Major road length within 100m (m)
    "TRAN_STP_C_100m",      # Transit stop count within 100m

    # -- Accessibility --
    "a_AM_IND",             # AM peak accessibility to industrial employment
    "a_AM_OFC",             # AM peak accessibility to office employment
    "a_PM_RTL",             # PM peak accessibility to retail employment
    "AIRP_DIST",            # Distance to nearest airport (m)
    "BSTP_DIST",            # Distance to nearest bus stop (m)
    "NBSTP_DIST",           # Distance to nearest commuter rail station (m)

    # -- Socio-demographics --
    "DAPOPDEN2021",         # Population density (DA level)

    # -- Policy --
    "GREENB",               # Binary: within Greenbelt (1/0)
]

# Model hyperparameters
RANDOM_SEED = 42
TEST_SIZE = 0.20           # Fraction held out for final testing
VAL_SIZE = 0.25            # Fraction of trainval held out for validation
LEARNING_RATE = 1e-3
BATCH_SIZE = 32
MAX_EPOCHS = 100
EARLY_STOP_PATIENCE = 10

# ==============================================================================
# DATA LOADING
# ==============================================================================

df = pd.read_csv(INPUT_PATH)

# Validate that required columns exist
missing_features = [c for c in FEATURE_COLUMNS if c not in df.columns]
if missing_features:
    raise ValueError(
        f"Missing feature columns in dataset: {missing_features}\n"
        f"Adapt FEATURE_COLUMNS to match your data."
    )
if LABEL_COLUMN not in df.columns:
    raise ValueError(f"Label column '{LABEL_COLUMN}' not found in dataset.")

X = df[FEATURE_COLUMNS].values
y = df[LABEL_COLUMN].values.astype(int)

print(f"Dataset: {len(df)} parcels, {X.shape[1]} features")
print(f"Label distribution: 0 (Saturated) = {np.sum(y == 0)}, "
      f"1 (Unsaturated) = {np.sum(y == 1)}")

# ==============================================================================
# TRAIN / VALIDATION / TEST SPLIT
# ==============================================================================
# Split into 60% train, 20% validation, 20% test (stratified by label).

X_trainval, X_test, y_trainval, y_test = train_test_split(
    X, y, test_size=TEST_SIZE, random_state=RANDOM_SEED, stratify=y
)
X_train, X_val, y_train, y_val = train_test_split(
    X_trainval, y_trainval, test_size=VAL_SIZE, random_state=RANDOM_SEED,
    stratify=y_trainval
)

print(f"Train: {len(X_train)}, Validation: {len(X_val)}, Test: {len(X_test)}")

# ==============================================================================
# FEATURE STANDARDISATION
# ==============================================================================
# Fit scaler on training data only; apply to validation and test.

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_val   = scaler.transform(X_val)
X_test  = scaler.transform(X_test)

# ==============================================================================
# MODEL DEFINITION
# ==============================================================================
# Two hidden layers with batch normalisation and dropout.
# This architecture is a starting point — tune layer sizes, dropout rates,
# and regularisation strength for your dataset.

model = Sequential([
    Dense(128, input_dim=X_train.shape[1], activation="relu",
          kernel_regularizer=tf.keras.regularizers.l2(1e-4)),
    BatchNormalization(),
    Dropout(0.25),

    Dense(64, activation="relu",
          kernel_regularizer=tf.keras.regularizers.l2(1e-4)),
    BatchNormalization(),
    Dropout(0.25),

    Dense(1, activation="sigmoid")
])

model.compile(
    optimizer=Adam(learning_rate=LEARNING_RATE),
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

model.summary()

# ==============================================================================
# CLASS WEIGHTS
# ==============================================================================
# Compensate for any remaining label imbalance in the training set.

cw = class_weight.compute_class_weight(
    "balanced", classes=np.unique(y_train), y=y_train
)
class_weights = {int(k): float(v) for k, v in zip(np.unique(y_train), cw)}
print(f"Class weights: {class_weights}")

# ==============================================================================
# CUSTOM CALLBACK — Comparable Inference-Mode Accuracy per Epoch
# ==============================================================================
# During training, Keras reports accuracy WITH dropout active, which is lower
# than the true accuracy. This callback evaluates in inference mode (dropout
# off) at the end of each epoch for a fair train-vs-val comparison.

class InferenceAccuracyCallback(tf.keras.callbacks.Callback):
    """Track train and validation accuracy in inference mode each epoch."""

    def __init__(self, X_train, y_train, X_val, y_val, threshold=0.5):
        super().__init__()
        self.X_train = X_train
        self.y_train = y_train
        self.X_val = X_val
        self.y_val = y_val
        self.threshold = threshold
        self.train_acc_history = []
        self.val_acc_history = []

    def on_epoch_end(self, epoch, logs=None):
        y_pred_train = (self.model.predict(self.X_train, verbose=0)
                        > self.threshold).astype(int).ravel()
        y_pred_val = (self.model.predict(self.X_val, verbose=0)
                      > self.threshold).astype(int).ravel()
        train_acc = accuracy_score(self.y_train, y_pred_train)
        val_acc = accuracy_score(self.y_val, y_pred_val)
        self.train_acc_history.append(train_acc)
        self.val_acc_history.append(val_acc)

# ==============================================================================
# TRAINING
# ==============================================================================

inference_cb = InferenceAccuracyCallback(X_train, y_train, X_val, y_val)
early_stopping = EarlyStopping(
    monitor="val_loss", patience=EARLY_STOP_PATIENCE, restore_best_weights=True
)

history = model.fit(
    X_train, y_train,
    epochs=MAX_EPOCHS,
    batch_size=BATCH_SIZE,
    validation_data=(X_val, y_val),
    class_weight=class_weights,
    callbacks=[early_stopping, inference_cb],
    verbose=1
)

# ==============================================================================
# EVALUATION ON HELD-OUT TEST SET
# ==============================================================================

test_loss, test_acc = model.evaluate(X_test, y_test, verbose=0)
print(f"\nTest Loss: {test_loss:.4f}, Test Accuracy: {test_acc:.4f}")

y_test_pred = (model.predict(X_test, verbose=0) > 0.5).astype(int).ravel()
print("\nClassification Report (Test Set):")
print(classification_report(y_test, y_test_pred,
                            target_names=["Saturated (0)", "Unsaturated (1)"]))
print("Confusion Matrix (Test Set):")
print(confusion_matrix(y_test, y_test_pred))

# ==============================================================================
# DIAGNOSTIC PLOTS
# ==============================================================================

fig, axes = plt.subplots(1, 2, figsize=(12, 4))

axes[0].plot(inference_cb.train_acc_history, label="Train (inference mode)")
axes[0].plot(inference_cb.val_acc_history, label="Validation (inference mode)")
axes[0].set_title("Accuracy (Inference Mode)")
axes[0].set_ylabel("Accuracy")
axes[0].set_xlabel("Epoch")
axes[0].legend(loc="lower right")

axes[1].plot(history.history["loss"], label="Train loss")
axes[1].plot(history.history["val_loss"], label="Validation loss")
axes[1].set_title("Loss")
axes[1].set_ylabel("Loss")
axes[1].set_xlabel("Epoch")
axes[1].legend(loc="upper right")

plt.tight_layout()
plt.savefig("saturation_classifier_training.png", dpi=150)
plt.show()
print("Training plot saved to saturation_classifier_training.png")
